<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.374" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JBF.Api\JBF.Api.csproj" />
  </ItemGroup>
  <Target Name="CopyMySqlConnector" AfterTargets="Build">
    <Copy SourceFiles="$(NuGetPackageRoot)mysqlconnector\2.5.0\lib\net10.0\MySqlConnector.dll"
          DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>
</Project>
