<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
    <Compile Include="Commands/**/*.cs" />
    <Compile Include="Database/**/*.cs" />
    <Compile Include="Functions/**/*.cs" />
    <Compile Include="Menu/**/*.cs" />
    <Compile Include="Menus/**/*.cs" />
    <Compile Include="Messages/**/*.cs" />

    <PackageReference Include="CoreRcon" Version="5.4.1"/>
    <PackageReference Include="dapper" Version="2.1.35"/>
    <PackageReference Include="mysqlconnector" Version="2.3.7"/>
    <PackageReference Include="SteamWebAPI2" Version="4.4.1"/>
    <PackageReference Include="CounterStrikeSharp.Api" Version="1.0.374"/>

    <ProjectReference Include="..\JBF.Api\JBF.Api.csproj"/>

    <Reference Include="IksAdminApi">
      <HintPath>..\RequirmentsApi\IksAdminApi.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <Target Name="ExportDllsAfterBuild" AfterTargets="Build">
    <ItemGroup>
      <SelectedDlls Include="$(TargetPath)"/>
      <SelectedDlls Include="$(OutputPath)\IksAdmin.pdb"/>
      <SelectedDlls Include="$(OutputPath)\IksAdminApi.dll"/>
      <SelectedDlls Include="$(OutputPath)\AutoMapper.dll"/>
      <SelectedDlls Include="$(OutputPath)\CoreRcon.dll"/>
      <SelectedDlls Include="$(OutputPath)\Dapper.dll"/>
      <SelectedDlls Include="$(OutputPath)\MySqlConnector.dll"/>
      <SelectedDlls Include="$(OutputPath)\Newtonsoft.Json.dll"/>
      <SelectedDlls Include="$(OutputPath)\Steam.Models.dll"/>
      <SelectedDlls Include="$(OutputPath)\SteamWebAPI2.dll"/>
      <SelectedDlls Include="$(OutputPath)\System.IO.Pipelines.dll"/>
    </ItemGroup>

    <ItemGroup>
      <SharedDlls Include="$(OutputPath)\IksAdminApi.dll"/>
    </ItemGroup>

    <ItemGroup>
      <LanguageFiles Include="$(MSBuildProjectDirectory)\lang\**\*"/>
      <ConfigFiles Include="$(MSBuildProjectDirectory)\configs\**\*"/>
      <SortMenuConfigFile Include="$(MSBuildProjectDirectory)\sortmenus.json"/>
    </ItemGroup>

    <MakeDir Directories="$(OutputPath)\bundle"/>
    <MakeDir Directories="$(OutputPath)\bundle\plugins\$(MSBuildProjectName)"/>
    <MakeDir Directories="$(OutputPath)\bundle\plugins\$(MSBuildProjectName)\lang"/>
    <MakeDir Directories="$(OutputPath)\bundle\shared\IksAdminApi"/>
    <MakeDir Directories="$(OutputPath)\bundle\configs\plugins\$(MSBuildProjectName)"/>

    <Copy SourceFiles="@(SelectedDlls)" DestinationFolder="$(OutputPath)\bundle\plugins\$(MSBuildProjectName)" SkipUnchangedFiles="true"/>
    <Copy SourceFiles="@(SharedDlls)" DestinationFolder="$(OutputPath)\bundle\shared\IksAdminApi" SkipUnchangedFiles="true"/>
    <Copy SourceFiles="@(LanguageFiles)"
          DestinationFolder="$(OutputPath)\bundle\plugins\$(MSBuildProjectName)\lang\%(RecursiveDir)"
          SkipUnchangedFiles="true"/>
    <Copy SourceFiles="@(ConfigFiles)"
          DestinationFolder="$(OutputPath)\bundle\configs\plugins\$(MSBuildProjectName)\%(RecursiveDir)"
          SkipUnchangedFiles="true"/>
    <Copy SourceFiles="@(SortMenuConfigFile)"
          DestinationFolder="$(OutputPath)\bundle\plugins\$(MSBuildProjectName)"
          SkipUnchangedFiles="true"/>
  </Target>

</Project>
